export const PAGE_SIZES = {
  EXTRA_SMALL_PAGE_SIZE: 5,
  SMALL_PAGE_SIZE: 10,
  DEFAULT_PAGE_SIZE: 25,
  MEDIUM_PAGE_SIZE: 50,
  LARGE_PAGE_SIZE: 100,
  MAX_PAGE_SIZE: 200,
} as const;

export const PAGE_SIZES_ARRAY = [
  PAGE_SIZES.SMALL_PAGE_SIZE,
  PAGE_SIZES.DEFAULT_PAGE_SIZE,
  PAGE_SIZES.MEDIUM_PAGE_SIZE,
  PAGE_SIZES.LARGE_PAGE_SIZE,
] as const;

export type PageSize = (typeof PAGE_SIZES_ARRAY)[number];
